import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/Toster";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("flex h-screen flex-col", inter.className)}>
        <Providers>
          <Header />
          <main className="container mx-auto max-w-6xl grow">{children}</main>
          {authModal}

          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
